# Generated by Django 4.1.3 on 2022-11-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitInplit',
            fields=[
                ('id_splitinplit', models.BigAutoField(primary_key=True, serialize=False)),
                ('proporcao_de', models.IntegerField(verbose_name='Proporção DE')),
                ('proporcao_para', models.IntegerField(verbose_name='Proporção PARA')),
                ('data_corte', models.DateField()),
                ('status', models.CharField(choices=[('S', 'FEITO'), ('N', 'NÃO FEITO')], default='N', max_length=1, verbose_name='Status')),
                ('data_exe', models.DateField(auto_now=True)),
                ('fk_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.empresaslistadas', verbose_name='Ticker')),
            ],
            options={
                'verbose_name_plural': 'Splits Inplits',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_notas', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Nota')),
                ('data_pregao', models.DateField(verbose_name='Data Pregão')),
                ('data_liquidacao', models.DateField(verbose_name='Data Liquidação')),
                ('fk_corretora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.corretora', verbose_name='Corretora')),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id_ativo', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('S', 'FEITO'), ('N', 'NÃO FEITO')], default='N', max_length=1, verbose_name='status nota')),
                ('operacao', models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA')], max_length=1, verbose_name='Operação')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço')),
                ('valor_operacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Operação')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor Liquido')),
                ('irrf', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='I.R.R.F')),
                ('taxa_liquidacao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Liquidação')),
                ('taxa_registro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Registro')),
                ('taxa_termo_opcoes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Termo Opções')),
                ('taxa_ana', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. A.N.A')),
                ('emolumentos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Emolumentos')),
                ('taxa_operacional', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Corretagem')),
                ('taxa_execucao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Execução')),
                ('taxa_custodia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Custódia')),
                ('imposto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Imposto / ISS')),
                ('outros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Outros')),
                ('fk_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.nota')),
                ('fk_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.empresaslistadas', verbose_name='Ticker')),
                ('fk_tipo_ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.tipoativo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Ativos',
            },
        ),
    ]
