# Generated by Django 4.1.3 on 2022-11-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0005_remove_empresaslistadas_saldo_corretora_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_notas', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=1, null=True, verbose_name='status nota')),
                ('nota', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Nota')),
                ('data_pregao', models.DateField(verbose_name='Data Pregão')),
                ('data_liquidacao', models.DateField(verbose_name='Data Liquidação')),
                ('fk_corretora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.corretora', verbose_name='Corretora')),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id_ativo', models.BigAutoField(primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA')], max_length=1, verbose_name='Operação')),
                ('tipo', models.CharField(choices=[('ACAO', 'AÇÃO'), ('ETF', 'ETF'), ('FII', 'FII'), ('BDR', 'BDR'), ('OPCAO', 'OPÇÃO'), ('FUTURO', 'FUTURO'), ('STOCK', 'STOCK'), ('REIT', 'REIT'), ('PREV.PRI', 'PREVIDENCIA PRIVADA')], max_length=20, verbose_name='Bairro')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço')),
                ('valor_operacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Operação')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor Liquido')),
                ('irrf', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='I.R.R.F')),
                ('taxa_liquidacao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa Liquidação')),
                ('taxa_registro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa Registro')),
                ('taxa_termo_opcoes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa Termo Opções')),
                ('taxa_ana', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa A.N.A')),
                ('emolumentos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Emolumentos')),
                ('taxa_operacional', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa Operacional')),
                ('taxa_execucao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa Execução')),
                ('taxa_custodia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Taxa Custódia')),
                ('imposto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Imposto')),
                ('outros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Outros')),
                ('fk_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.nota')),
                ('fk_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.empresaslistadas', verbose_name='Ticker')),
            ],
            options={
                'verbose_name_plural': 'Ativos',
            },
        ),
    ]
