# Generated by Django 4.1.3 on 2022-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='irrf_dt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='I.R.R.F Day Trade'),
        ),
    ]
