# Generated by Django 4.1.3 on 2022-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='taxa_ana',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. A.N.A'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='taxa_custodia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Custódia'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='taxa_execucao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Execução'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='taxa_liquidacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Liquidação'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='taxa_operacional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Operacional'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='taxa_registro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Registro'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='taxa_termo_opcoes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='T. Termo Opções'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(choices=[('ACAO', 'AÇÃO'), ('ETF', 'ETF'), ('FII', 'FII'), ('BDR', 'BDR'), ('OPCAO', 'OPÇÃO'), ('FUTURO', 'FUTURO'), ('STOCK', 'STOCK'), ('REIT', 'REIT'), ('PREV.PRI', 'PREVIDENCIA PRIVADA')], max_length=20, verbose_name='Tipo'),
        ),
    ]
