# Generated by Django 4.1.3 on 2022-11-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_remove_empresaslistadas_saldo_corretora_saldo'),
        ('notas', '0002_alter_ativo_taxa_ana_alter_ativo_taxa_custodia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitInplit',
            fields=[
                ('id_splitinplit', models.BigAutoField(primary_key=True, serialize=False)),
                ('proporcao_de', models.IntegerField(verbose_name='Proporção DE')),
                ('proporcao_para', models.IntegerField(verbose_name='Proporção PARA')),
                ('data_corte', models.DateField()),
                ('fk_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.empresaslistadas', verbose_name='Ticker')),
            ],
            options={
                'verbose_name_plural': 'Splits Inplits',
            },
        ),
    ]
