# Generated by Django 4.1.3 on 2022-11-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_ativo_daytrade_notadaytrade_ativodaytrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='daytrade',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, verbose_name='DayTrade'),
        ),
    ]
