# Generated by Django 4.1.3 on 2022-11-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_splitinplit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='status',
        ),
        migrations.AddField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('S', 'FEITO'), ('N', 'NÃO FEITO')], default='N', max_length=1, verbose_name='status nota'),
        ),
    ]
