# Generated by Django 4.1.3 on 2022-11-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_remove_nota_status_ativo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitinplit',
            name='status',
            field=models.CharField(choices=[('S', 'FEITO'), ('N', 'NÃO FEITO')], default='N', max_length=1, verbose_name='Status'),
        ),
    ]
