# Generated by Django 4.1.3 on 2022-11-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0005_remove_empresaslistadas_saldo_corretora_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_pregao', models.DateField(verbose_name='Data Pregão')),
                ('data_liquidacao', models.DateField(verbose_name='Data Liquidação')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('fk_corretora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.corretora')),
            ],
            options={
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
