# Generated by Django 4.1.3 on 2022-11-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_ativo_taxa_ana_alter_ativo_taxa_custodia_and_more'),
        ('movimentacoes', '0002_movimentacao_fk_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='fk_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notas.ativo', verbose_name='Ativo'),
        ),
    ]
