# Generated by Django 4.1.3 on 2022-11-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretora',
            name='ativa',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], default=0, max_length=1, verbose_name='Ativa'),
            preserve_default=False,
        ),
    ]
