# Generated by Django 4.1.3 on 2022-11-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_corretora_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresasListadas',
            fields=[
                ('id_empresas_listadas', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=30, verbose_name='Ticker')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='Nº CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
            ],
            options={
                'verbose_name_plural': 'Empresas Listadas',
            },
        ),
    ]
