# Generated by Django 4.1.3 on 2022-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_empresaslistadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaslistadas',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo'),
        ),
    ]
